version: "2"

services:
  dukecon-httpd:
    image: dukecon/dukecon-httpd:latest
    build:
      context: httpd
  dukecon-maven:
    image: dukecon/dukecon-maven:latest
    build:
      context: maven
  dukecon-node:
    image: dukecon/dukecon-node:latest
    build:
      context: node
